"""Core Agent class."""

import asyncio
import logging
from datetime import datetime
from typing import Any, AsyncGenerator, Dict, List, Optional

from .agent_loop import run_agent_loop
from .constants import MAX_AGENT_ROUNDS
from .llm import LLMProvider
from .tools.base import Tool

logger = logging.getLogger(__name__)


class Agent:
    """Autonomous AI agent backed by a real LLM provider.

    Example (sync)::

        from agents import Agent
        from agents.llm import AnthropicProvider

        provider = AnthropicProvider(api_key="sk-ant-...")
        agent = Agent(name="MyAgent", provider=provider)
        result = agent.execute("Summarise the Zen of Python")

    Example (async streaming)::

        async for chunk in agent.stream("Write a haiku"):
            print(chunk, end="", flush=True)
    """

    def __init__(
        self,
        name: str,
        provider: LLMProvider,
        system_prompt: Optional[str] = None,
        tools: Optional[List[Tool]] = None,
        max_rounds: int = MAX_AGENT_ROUNDS,
    ):
        self.name = name
        self.provider = provider
        self.system_prompt = system_prompt or f"You are {name}, a helpful AI agent."
        self.tools: Dict[str, Tool] = {t.name: t for t in (tools or [])}
        self.max_rounds = max_rounds
        self.created_at = datetime.now()
        self.state: Dict[str, Any] = {}
        logger.info("Initialized agent '%s' with %d tool(s)", self.name, len(self.tools))

    # ── Public interface ──────────────────────────────────────────────────

    def execute(self, task: str, history: Optional[List[Dict]] = None) -> str:
        """Run the agent synchronously and return the full response.

        Wraps the async execution in `asyncio.run()`. Must NOT be called from
        within a running event loop — use `await agent.aexecute()` instead.
        """
        return asyncio.run(self._execute_async(task, history))

    async def aexecute(self, task: str, history: Optional[List[Dict]] = None) -> str:
        """Async variant of `execute()` — use this from async code."""
        return await self._execute_async(task, history)

    async def stream(
        self, task: str, history: Optional[List[Dict]] = None
    ) -> AsyncGenerator[str, None]:
        """Stream response chunks from the agent loop.

        Yields text as it's generated by the LLM. Tool calls are executed
        transparently between rounds; only final text content is yielded.
        """
        messages = self._build_messages(task, history)
        async for chunk in run_agent_loop(
            provider=self.provider,
            messages=messages,
            tools=self.tools,
            max_rounds=self.max_rounds,
        ):
            yield chunk

    # ── State management ──────────────────────────────────────────────────

    def get_state(self) -> Dict[str, Any]:
        """Return agent metadata and custom state."""
        return {
            "name": self.name,
            "model": getattr(self.provider, "model", None),
            "created_at": self.created_at.isoformat(),
            "tools": list(self.tools.keys()),
            "state": self.state,
        }

    def update_state(self, key: str, value: Any) -> None:
        """Store an arbitrary value in the agent's state dict."""
        self.state[key] = value
        logger.debug("Agent '%s' state updated: %s=%r", self.name, key, value)

    # ── Internal ──────────────────────────────────────────────────────────

    def _build_messages(
        self, task: str, history: Optional[List[Dict]] = None
    ) -> List[Dict]:
        messages = [{"role": "system", "content": self.system_prompt}]
        if history:
            messages.extend(history)
        messages.append({"role": "user", "content": task})
        return messages

    async def _execute_async(self, task: str, history: Optional[List[Dict]] = None) -> str:
        chunks: list[str] = []
        async for chunk in self.stream(task, history):
            chunks.append(chunk)
        return "".join(chunks)